

//Declarative
pipeline {
	agent any
	
	environment{
		dockerHome = tool 'myDocker'
		mavenHome = tool 'my-maven'
		PATH = "$dockerHome/bin:$mavenHome/bin:$PATH"
	}

	stages{
	      stage('Build'){
		steps{
			sh 'mvn --version'
			sh 'docker version'
			echo "Build"
		}
	      }
	      stage('Test'){
		steps{
			echo "Test"
		}
	      }
	      stage('Integration Test'){
		steps{
			echo "Integration Test"
		}
	      }
	}
	post{
		always{
			echo 'im awesome. i run always.'
		}
		success{
			echo 'i run when you are successfull.'
		}

		failure{
			echo 'i run when you fail.'
		}
	}


	
}
